# Generated by Django 5.1.3 on 2024-11-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloan',
            name='customer_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
